spring:
  rabbitmq:
    host: localhost
    port: 5672

# 1.0 means 100%, see http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sampling
spring.sleuth.sampler.percentage: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
defaultZone: http://localhost:8761/eureka/