server:
  port: 8072

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
        path: /uaa/**
        # serviceId: ???
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:
    authorized-client-service:
        path: /uaa/**
        #serviceId: ??? ебанная хуйня сука это ваш спринг клауд хуй просышь что куда и как аааааа
        url: http://authorized-client-service:5001
        stripPrefix: false
        sensitiveHeaders: