version: '3'

services:

#############################################################
# Core infrastructure
#############################################################
  gateway:
    build: gateway
    restart: always

  eureka:
    build: eureka
    restart: always

  config-service:
    build: config-service
    restart: always

  auth-service:
    build: auth-service
    restart: always

  zipkin:
    build: zipkin-server
    restart: always

#############################################################
# Native
#############################################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672

#############################################################
# Business services
#############################################################
  authorized-client-service:
    build: authorized-client-service
    restart: always